---
parser: babel-eslint
plugins:
- prettier
extends:
- prettier
- eslint:recommended
- plugin:react/recommended
rules:
  prettier/prettier: error
globals:
  graphql: true
overrides:
- files: "gatsby-*.js"
  env:
    node: true
